fix aliasing when running inside jest
It looks like when running the loader from jest, `process.env` looks up
the env property on the `process` function instead of the global object.
This results in errors like the following:

```
 FAIL  test/jest_test.re
  ● Test suite failed to run

    TypeError: process.cwd is not a function

      at Function.process (node_modules/bs-loader/index.js:108:13)
          at Generator.next (<anonymous>)
```

I renamed the `process` function to something else to remove this name
aliasing issue.